# Generated by Django 4.1.6 on 2023-08-09 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0005_inventoryactivities_created_at_formatted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryactivities',
            name='created_at_formatted',
        ),
    ]
