# Generated by Django 4.1.6 on 2023-08-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0007_inventoryactivities_created_at_formatted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryactivities',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
