# Generated by Django 4.1.6 on 2023-08-13 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0008_alter_inventoryactivities_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryactivities',
            name='created_at_formatted',
        ),
    ]
