version: "3"

services:
  dermage_app:
    container_name: dermage_app
    image: postgres
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      PGDATA: /data/dermage_app
    volumes:
      - dermage_app:/data/dermage_app
    ports:
      - "5434:5432"
    networks:
      - dermage_app_net
    restart: unless-stopped

networks:
  dermage_app_net:
    driver: bridge

volumes:
  dermage_app:
