version: "3"

services:
  dermage_app:
    container_name: dermage_app
    image: postgres
    environment:
<<<<<<< HEAD
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      PGDATA: /data/dermage_app
=======
      POSTGRES_USER: "pgadmin"
      POSTGRES_PASSWORD: "dermage01#"
      PGDATA: /data/inventory_app
>>>>>>> c8732a03cd82c160ec2433d0493aafb384c15417
    volumes:
      - dermage_app:/data/dermage_app
    ports:
      - "5434:5432"
    networks:
      - dermage_app_net
    restart: unless-stopped

networks:
  dermage_app_net:
    driver: bridge

volumes:
  dermage_app:
