# Generated by Django 3.2.6 on 2023-03-19 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0003_invoice_invoiceitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('inventory_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_control.inventorygroup')),
            ],
        ),
    ]
