# Generated by Django 3.2.6 on 2023-03-20 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0004_colaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='colabador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaborador', to='app_control.colaborador'),
        ),
    ]
