# Generated by Django 3.2.6 on 2023-03-20 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0005_inventory_colabador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='code',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='group',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='price',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='remaining',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='total',
        ),
        migrations.AddField(
            model_name='inventory',
            name='configuracao',
            field=models.TextField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='empresa',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='hostname',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories', to='app_control.inventorygroup'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='marca',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='modelo',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='nf_so',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='patriominio',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='service_tag',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='sistema_operacional',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
