# Generated by Django 3.2.6 on 2023-03-20 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0006_auto_20230319_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='colabador',
            new_name='colaborador',
        ),
    ]
