# Generated by Django 3.2.6 on 2023-03-21 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0007_rename_colabador_inventory_colaborador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='patriominio',
            new_name='patrimonio',
        ),
    ]
