# Generated by Django 3.2.6 on 2023-03-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0008_rename_patriominio_inventory_patrimonio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaborador',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='colaborador',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
