# Generated by Django 4.1.6 on 2023-03-22 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_control', '0009_auto_20230321_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboratte', to=settings.AUTH_USER_MODEL),
        ),
    ]
