# Generated by Django 4.1.6 on 2023-03-22 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0010_colaborador_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='local',
            new_name='group',
        ),
    ]
