# Generated by Django 4.1.6 on 2023-03-22 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_control', '0011_rename_local_inventory_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='inventory_group',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='belongs_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colab_relations', to='app_control.inventorygroup'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaborador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
