# Generated by Django 4.1.6 on 2023-03-22 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0012_remove_colaborador_inventory_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='group',
            new_name='local',
        ),
    ]
