# Generated by Django 3.2.6 on 2023-03-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0013_rename_group_inventory_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='configuracao',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='empresa',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='hostname',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='marca',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='modelo',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='service_tag',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='sistema_operacional',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
