# Generated by Django 3.2.6 on 2023-03-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0014_auto_20230323_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='hostname',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='nf_so',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='patrimonio',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='service_tag',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
