# Generated by Django 3.2.6 on 2023-03-24 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_control', '0015_auto_20230323_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory_Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimonio', models.PositiveIntegerField(null=True, unique=True)),
                ('hostname', models.CharField(max_length=10, null=True, unique=True)),
                ('sistema_operacional', models.CharField(max_length=10, null=True)),
                ('service_tag', models.CharField(max_length=10, null=True, unique=True)),
                ('nf_so', models.PositiveIntegerField(null=True, unique=True)),
                ('empresa', models.CharField(max_length=50, null=True)),
                ('marca', models.CharField(max_length=10, null=True)),
                ('modelo', models.CharField(max_length=10, null=True)),
                ('configuracao', models.TextField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaborador_notebook', to='app_control.colaborador')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_notebook_items', to=settings.AUTH_USER_MODEL)),
                ('local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories_notebook', to='app_control.inventorygroup')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Inventory_Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimonio', models.PositiveIntegerField(null=True, unique=True)),
                ('marca', models.CharField(max_length=10, null=True)),
                ('modelo', models.CharField(max_length=10, null=True)),
                ('imei', models.CharField(max_length=500, null=True)),
                ('nf', models.CharField(max_length=50, null=True)),
                ('linha', models.CharField(max_length=50, null=True)),
                ('obs', models.TextField(max_length=500, null=True)),
                ('colaborador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaborador_mobile', to='app_control.colaborador')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_mobile_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_by',),
            },
        ),
        migrations.CreateModel(
            name='Inventory_Datacenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=10, null=True, unique=True)),
                ('descricao', models.CharField(max_length=10, null=True)),
                ('hostname', models.CharField(max_length=10, null=True, unique=True)),
                ('sistema_operacional', models.CharField(max_length=10, null=True)),
                ('service_tag', models.CharField(max_length=10, null=True, unique=True)),
                ('nf_so', models.PositiveIntegerField(null=True, unique=True)),
                ('empresa', models.CharField(max_length=50, null=True)),
                ('marca', models.CharField(max_length=10, null=True)),
                ('modelo', models.CharField(max_length=10, null=True)),
                ('configuracao', models.TextField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaborador_datacenter', to='app_control.colaborador')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_datacenter_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
