# Generated by Django 3.2.6 on 2023-05-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0016_inventory_datacenter_inventory_mobile_inventory_notebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='modelo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='nf_so',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inventory_datacenter',
            name='modelo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventory_datacenter',
            name='nf_so',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inventory_mobile',
            name='modelo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventory_notebook',
            name='modelo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventory_notebook',
            name='nf_so',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
