# Generated by Django 3.2.6 on 2023-05-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0017_auto_20230510_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='usuario',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
