# Generated by Django 4.1.6 on 2023-05-29 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0017_inventory_usuario_inventory_mobile_usuario_and_more'),
        ('app_control', '0018_inventory_usuario'),
    ]

    operations = [
    ]
