# Generated by Django 4.1.6 on 2023-06-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0020_alter_inventory_mobile_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='service_tag',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inventory_notebook',
            name='service_tag',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
