# Generated by Django 4.1.6 on 2023-06-07 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0021_alter_inventory_service_tag_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaborador',
            options={'ordering': ('id',)},
        ),
    ]
