# Generated by Django 4.1.6 on 2023-06-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0023_alter_colaborador_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_datacenter',
            name='hostname',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inventory_datacenter',
            name='service_tag',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inventory_datacenter',
            name='sistema_operacional',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
