# Generated by Django 4.1.6 on 2023-06-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0024_alter_inventory_datacenter_hostname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_datacenter',
            name='descricao',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='inventory_datacenter',
            name='ip',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inventory_datacenter',
            name='marca',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
