# Generated by Django 4.1.6 on 2023-06-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0025_alter_inventory_datacenter_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_mobile',
            name='marca',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
