# Generated by Django 4.1.6 on 2023-07-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0026_alter_inventory_mobile_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='service_tag',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inventory_datacenter',
            name='service_tag',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='inventory_notebook',
            name='service_tag',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
