# Generated by Django 4.1.6 on 2023-07-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0027_alter_inventory_service_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='patrimonio',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inventory_mobile',
            name='patrimonio',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inventory_notebook',
            name='patrimonio',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
