# Generated by Django 4.1.6 on 2023-07-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0028_alter_inventory_patrimonio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='hostname',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inventory_notebook',
            name='hostname',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
    ]
