# Generated by Django 4.1.6 on 2023-07-19 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0029_alter_inventory_hostname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='item',
        ),
        migrations.AlterModelOptions(
            name='inventorygroup',
            options={'ordering': ('-id',)},
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
