# Generated by Django 4.1.6 on 2023-08-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0030_remove_invoiceitem_invoice_remove_invoiceitem_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='configuracao',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='inventory_datacenter',
            name='configuracao',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='inventory_notebook',
            name='configuracao',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
