# Generated by Django 4.1.6 on 2023-08-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0031_alter_inventory_configuracao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorygroup',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inventorygroup',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
