# Generated by Django 4.1.6 on 2023-08-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0032_alter_inventorygroup_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='motivo_depreciado',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='inventory_datacenter',
            name='motivo_depreciado',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='inventory_mobile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory_mobile',
            name='motivo_depreciado',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='inventory_mobile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inventory_notebook',
            name='motivo_depreciado',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
