# Generated by Django 4.1.6 on 2023-08-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0033_inventory_motivo_depreciado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorygroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inventorygroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
